### PR TITLE
Fixes a bunch of bugs & tweaked the magic door

### LINKED ISSUE #13: Early registration issue
Been having an issue where Arcanus Continuum conflicts with other quilt-specific mods such as Auroras Decorations, Bumblezone (Quilt version) or Tablesaw. It mentions that the spells are being registered too early. The mod pack I'm making launches fine without the mod installed now.

It seems like a new error because I've been using it fine for a while but recently it cropped up. I don't entirely know what caused it though.

**Log**: https://gist.github.com/sleepy-evelyn/066e1c57bc8cbad3c7b64266a2183866
**Quilt Version**: 0.21.0-beta4
**Mod Version**: 0.101.1
**MC Version**: 1.20.1

### PR DESCRIPTION
**Pull request by EvieTheOwl**
## Fixes the following bugs
- **#13 Early null registration** - Checked if the entity attributes are initialized or not so a null value isn't returned by another mod when they hit the entity registration phase. Prevents mods that register before this one from causing a crash.

- **Spawn eggs spawning pigs** - Placed entity type registration before item registration

- Checks for the owner of the door by UUID instead of the living entity object which didn't work

- Fixes a crash that happens when giving the magic door a new password. Data was being sent to the client so it returned a null value.

- Fixed spell book screens overlaying the foreground spell information between books by removing the `static` declaration from the screen handler.

## Also some tweaks
- Now displays a message when a magic door is given a new password

- Magic door now also accepts the lowercase version of the original password. CaSe sensitive feels like a bad idea for this. Feel free to revert if u disagree

- Doubled spacing and separation for wizard towers. Found when testing in a modpack I'm making atm that they generate way too frequently

### CODE REVIEW

File: src/main/java/dev/cammiescorner/arcanuscontinuum/common/entities/living/OpossumEntity.java [hunk 1]
```diff
@@ -47,7 +47,8 @@
 import java.util.UUID;
 
 @SuppressWarnings("ALL")
-public class OpossumEntity extends TameableEntity implements SmartBrainOwner<OpossumEntity> {
+public class
+OpossumEntity extends TameableEntity implements SmartBrainOwner<OpossumEntity> {
```
Comment (UpcraftLP) [inline src/main/java/dev/cammiescorner/arcanuscontinuum/common/entities/living/OpossumEntity.java:51]: unnecessary formatting change

File: src/main/java/dev/cammiescorner/arcanuscontinuum/common/blocks/MagicDoorBlock.java [hunk 2]
```diff
@@ -53,17 +57,23 @@ public void scheduledTick(BlockState state, ServerWorld world, BlockPos pos, Ran
...
 		ItemStack stack = player.getStackInHand(hand);
 		MagicDoorBlockEntity door = getBlockEntity(world, state, pos);
+		LivingEntity owner = door.getOwner();
 
-		if(stack.isOf(Items.NAME_TAG) && stack.hasCustomName() && door != null)
-			if(door.getOwner().equals(player))
-				door.setPassword(stack.getName().getString());
-			else
+		if(owner != null && stack.isOf(Items.NAME_TAG) && stack.hasCustomName())
+			if(owner.getUuid().compareTo(player.getUuid()) == 0) {
```
Comment (UpcraftLP) [inline src/main/java/dev/cammiescorner/arcanuscontinuum/common/blocks/MagicDoorBlock.java]: any reason for using `compareTo()` instead of `equals()`?

File: src/main/java/dev/cammiescorner/arcanuscontinuum/common/blocks/MagicDoorBlock.java [hunk 3]
```diff
@@ -27,6 +29,8 @@
 import org.quiltmc.qsl.block.extensions.api.QuiltBlockSettings;
 import org.quiltmc.qsl.item.setting.api.QuiltItemSettings;
 
+import java.util.Locale;
```
Comment (UpcraftLP) [inline src/main/java/dev/cammiescorner/arcanuscontinuum/common/blocks/MagicDoorBlock.java]: random import

File: src/main/java/dev/cammiescorner/arcanuscontinuum/Arcanus.java [hunk 4]
```diff
@@ -169,14 +171,16 @@ public void onInitialize(ModContainer mod) {
 					for(BlockPos pos : pointOfInterest.collect(Collectors.toSet())) {
 						BlockState state = world.getBlockState(pos);
 
-						if(state.getBlock() instanceof MagicDoorBlock doorBlock && world.getBlockEntity(pos) instanceof MagicDoorBlockEntity door && message.equals(door.getPassword())) {
-							doorBlock.setOpen(null, world, state, pos, true);
-							player.sendMessage(translate("door", "access_granted").formatted(Formatting.GRAY, Formatting.ITALIC), true);
+						if(state.getBlock() instanceof MagicDoorBlock doorBlock && world.getBlockEntity(pos) instanceof MagicDoorBlockEntity door) {
+							boolean messageIsPassword = message.equals(door.getPassword()) || message.equals(door.getPassword().toLowerCase());
```
Comment (UpcraftLP) [inline src/main/java/dev/cammiescorner/arcanuscontinuum/Arcanus.java]: If you're adding the lowercase version, perhaps it would be best to just ignore casing (by lowercasing both the input and the stored password before comparing).

Also please use the locale-independent version of `toLowerCase()` by passing `Locale.ROOT`.

File: src/main/java/dev/cammiescorner/arcanuscontinuum/Arcanus.java [hunk 5]
```diff
@@ -145,8 +145,10 @@ public void onInitialize(ModContainer mod) {
 		});
 
 		ResourceLoaderEvents.END_DATA_PACK_RELOAD.register(ctx -> {
-			if(ctx.server() != null)
-				Arcanus.refreshSupporterData(ctx.server(), true);
+			try (MinecraftServer server = ctx.server()) {
```
Comment (UpcraftLP) [inline src/main/java/dev/cammiescorner/arcanuscontinuum/Arcanus.java]: wrapping this in a try-with-resources statement will cause java to close the server object at the end of that statement

**Review by UpcraftLP — CHANGES_REQUESTED** [review]

File: src/main/java/dev/cammiescorner/arcanuscontinuum/common/entities/living/OpossumEntity.java (hunk 1 above)
Comment (EvieTheOwl) [reply src/main/java/dev/cammiescorner/arcanuscontinuum/common/entities/living/OpossumEntity.java:51]: That's kind of weird lol I didn't change the formatting. Might have happened by mistake.

File: src/main/java/dev/cammiescorner/arcanuscontinuum/common/blocks/MagicDoorBlock.java (hunk 2 above)
Comment (EvieTheOwl) [reply src/main/java/dev/cammiescorner/arcanuscontinuum/common/blocks/MagicDoorBlock.java]: Nope lol my mistake

File: src/main/java/dev/cammiescorner/arcanuscontinuum/common/blocks/MagicDoorBlock.java (hunk 3 above)
Comment (EvieTheOwl) [reply src/main/java/dev/cammiescorner/arcanuscontinuum/common/blocks/MagicDoorBlock.java]: Optimised imports :)

File: src/main/java/dev/cammiescorner/arcanuscontinuum/Arcanus.java (hunk 4 above)
Comment (EvieTheOwl) [reply src/main/java/dev/cammiescorner/arcanuscontinuum/Arcanus.java]: You're right. Just stored the lowercase password and compared to it now

File: src/main/java/dev/cammiescorner/arcanuscontinuum/Arcanus.java (hunk 5 above)
Comment (EvieTheOwl) [reply src/main/java/dev/cammiescorner/arcanuscontinuum/Arcanus.java]: Oops

**Review by EvieTheOwl — COMMENTED** [review]
Should have fixed the PR issues

**Comment by EvieTheOwl** [comment]
Just some notes on the wizard tower stuff. I figured it makes sense for nearly every wizard tower to have at least 1 spell book. I tested this by flying around in creative and found rarely I would find a single one. 

I've increased the chances of generating a spell book. I think duplicate spell books are fine as well because u can save for later or give to a friend on a multiplayer server. Lemme know if u disagree though.

I also increased the spacing between consecutive structure generation attempts because I noticed on the modpack I was using they tended to generate waaaaay too frequently for what is quite a large structure with no variants at the moment. I'm guessing more structures are planned for the future tho other than the tower

**Review by UpcraftLP — APPROVED** [review]
Looking good now 👍🏻

**Comment by sleepy-evelyn** [comment]
Yay it passed haha
